#!/usr/bin/env bash

### Bash Environment Setup
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
# set -o xtrace
set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
IFS=$'\n'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set default value for ACTIVATE_VENV if not defined
: "${ACTIVATE_VENV:=1}"

if [[ "$ACTIVATE_VENV" != "0" ]]; then
    source "$DIR/.venv/bin/activate" || echo "[X] Failed to source $DIR"
fi

txtbld=$(tput bold)
normal=$(tput sgr0)
red=${txtbld}$(tput setaf 1)
blue=${txtbld}$(tput setaf 4)
green=${txtbld}$(tput setaf 2)
white=${txtbld}$(tput setaf 7)
current_branch=$(git rev-parse --abbrev-ref HEAD)
LOCAL_RSYNC="${LOCAL_DEPLOY:-0}"

# Set default port if not defined
: "${PORT:=5000}"

echo "${blue}[+] Starting Flask server to render pages...$normal"
./server --port $PORT > /dev/null &
sleep 1.5

# Recreate output folder
rm -Rf docs
mkdir -p docs/posts
mkdir -p docs/jobs
mkdir -p docs/reports
mkdir -p docs/webinars


cp -r static docs/static
cp -r static/.well-known docs/.well-known
cp CNAME docs/CNAME
cp static/favicon.ico docs/favicon.ico
cp static/robots.txt docs/robots.txt
cp static/_config.yml docs/_config.yml
./server --pages > docs/pages.txt
./server --posts > docs/posts.txt
./server --jobs > docs/jobs.txt
./server --rates > docs/rates.txt
./server --reports > docs/reports.txt
./server --webinars > docs/webinars.txt
echo ""
echo "${blue}[+] Saving pages as static HTML to output/...$normal"
(cd docs; if [ -s pages.txt ]; then wget -q --no-check-certificate $(<pages.txt); fi)
(cd docs/posts; if [ -s ../posts.txt ]; then wget -q --no-check-certificate $(<../posts.txt); fi)
(cd docs/jobs; if [ -s ../jobs.txt ]; then wget -q --no-check-certificate $(<../jobs.txt); fi)
(cd docs/reports; if [ -s ../reports.txt ]; then wget -q --no-check-certificate $(<../reports.txt); fi)
(cd docs/webinars; if [ -s ../webinars.txt ]; then wget -q --no-check-certificate $(<../webinars.txt); fi)
(cd docs; if [ -s rates.txt ]; then wget -q --no-check-certificate $(<../rates.txt); fi)

echo ""
echo "${blue}[+] Saving rss feed as static XML to output/...$normal"
(cd docs/posts/; wget -q --no-check-certificate http://127.0.0.1:$PORT/posts/feed.xml)

echo ""
echo "${blue}[+] Including stevie king to docs/...$normal"
rsync -avh stevie-king/ docs/publishing/

echo ""
echo "${blue}[+] Delete '=' in fenced codes with line numbers...$normal"
grep -lrE "\`\`\`\w*=" ./docs/posts | xargs sed -i -r "s/(\`\`\`[a-zA-Z0-9]+)=/\1/g"

kill %1 > /dev/null
echo ""
echo "${green}[√] Build of static site to docs/ complete.$normal"
echo "    Commit and push the build to master, then wait ~2-5 minutes for the changes to show up on https://monadical.com"
