const jsonPostSchema = {
  $schema: 'http://json-schema.org/draft-07/schema',
  type: 'object',
  format: 'grid',
  title: 'Blog Post Data',
  default: {},
  examples: [
    {
      date: '2020-03-18',
      img: '/static/remote-work.jpg',
      title: 'How to Make Remote Work: Part One',
      tags: [
        'Management',
        'Transparency',
        'Teambuilding',
        'Process',
      ],
      length: '10 min read',
      source: 'https://docs.monadical.com/s/how-to-make-remote-work-part-one',
      url: '/posts/how-to-make-remote-work-part-one.html',
      template: 'posts/how-to-make-remote-work-part-one.html',
      description: 'How to build asynchronous processes that enable you to work efficiently with a distributed engineering team.',
      author: {
        name: 'Nick Sweeting',
        title: 'Monadical CTO',
        handle: '@thsquashsh',
        url: 'https://twitter.com/thsquashsh',
        image: '/static/nick.jpg',
      },
    },
  ],
  required: [
    'date',
    'img',
    'title',
    'tags',
    'length',
    'source',
    'url',
    'template',
    'description',
    'author',
  ],
  additionalProperties: true,
  properties: {
    title: {
      $id: '#/properties/title',
      type: 'string',
      title: 'Title',
      maxLength: 60,
      minLength: 10,
      description: 'Post\'s Title',
      default: '',
      examples: [
        'How to Make Remote Work: Part One',
      ],
    },
    description: {
      $id: '#/properties/description',
      type: 'string',
      format: 'textarea',
      title: 'Description',
      maxLength: 320,
      minLength: 10,
      description: 'A brief summary of your post',
      default: '',
      examples: [
        'How to build asynchronous processes that enable you to work efficiently with a distributed engineering team.',
      ],
    },
    date: {
      $id: '#/properties/date',
      type: 'string',
      format: 'date',
      title: 'Publication Date',
      default: '',
      examples: [
        '2020-03-18',
      ],
    },
    img: {
      $id: '#/properties/img',
      type: 'string',
      format: 'uri',
      title: 'Image URL',
      pattern: '^/static/(.+)$',
      description: 'Post\'s image upload URL i.e /static/how-to-make-remote-work (extension will match uploaded file)',
      default: '',
      examples: [
        '/static/remote-work.jpg',
      ],
    },
    tags: {
      $id: '#/properties/tags',
      type: 'array',
      uniqueItems: true,
      maxContains: 5,
      title: 'Tags',
      default: [],
      examples: [
        [
          'Management',
          'Transparency',
        ],
      ],
      additionalItems: true,
      items: {
        anyOf: [
          {
            $id: '#/properties/tags/items/anyOf/0',
            type: 'string',
            title: 'Tag',
            description: 'An explanation about the purpose of this instance.',
            default: '',
            examples: [
              'Management',
              'Transparency',
            ],
          },
        ],
        $id: '#/properties/tags/items',
      },
    },
    length: {
      $id: '#/properties/length',
      type: 'number',
      format: 'range',
      title: 'Reading time',
      minimum: 1,
      maximum: 60,
      description: 'An estimate of the reading time i.e 5 min read',
      default: '',
      examples: [
        '10 min read',
      ],
    },
    source: {
      $id: '#/properties/source',
      type: 'string',
      pattern: '^https://docs[.]monadical[.]com/s/(.+)$',
      title: 'Source',
      description: 'A url to the published article on docs.monadical.com',
      default: '',
      examples: [
        'https://docs.monadical.com/s/how-to-make-remote-work-part-one',
      ],
    },
    url: {
      $id: '#/properties/url',
      type: 'string',
      title: 'Post URL',
      pattern: '^/posts/(.+)$',
      description: 'ie./posts/how-to-make-remote-work-part-one.html',
      default: '',
      examples: [
        'i.e /posts/how-to-make-remote-work-part-one.html',
      ],
    },
    template: {
      $id: '#/properties/template',
      type: 'string',
      title: 'Template',
      pattern: '^posts/(.+)$',
      description: 'posts/how-to-make-remote-work-part-one.html',
      default: '',
      examples: [
        'posts/how-to-make-remote-work-part-one.html',
      ],
    },
    author: {
      $id: '#/properties/author',
      type: 'object',
      format: 'grid',
      title: 'Author',
      default: {},
      examples: [
        {
          name: 'Nick Sweeting',
          title: 'Monadical CTO',
          handle: '@thesquashsh',
          url: 'https://twitter.com/thesquashsh',
          image: '/static/nick.jpg',
        },
      ],
      required: [
        'name',
        'title',
        'handle',
        'url',
        'image',
      ],
      additionalProperties: true,
      properties: {
        name: {
          $id: '#/properties/author/properties/name',
          type: 'string',
          title: 'Author´s name',
          minLength: 2,
          description: 'Your full name',
          default: '',
          examples: [
            'Nick Sweeting',
          ],
        },
        title: {
          $id: '#/properties/author/properties/title',
          type: 'string',
          title: 'Company Title',
          description: 'Your company title',
          default: '',
          examples: [
            'Monadical CTO',
          ],
        },
        handle: {
          $id: '#/properties/author/properties/handle',
          type: 'string',
          minLength: 2,
          title: 'Social media handle',
          description: 'i.e @thesquashsh',
          pattern: '^@(.+)$',
          default: '',
          examples: [
            '@thesquashsh',
          ],
        },
        url: {
          $id: '#/properties/author/properties/url',
          type: 'string',
          format: 'url',
          title: 'Social media handle URL',
          description: 'A link to your profile in social media',
          default: '',
          examples: [
            'https://twitter.com/thesquashsh',
          ],
        },
        image: {
          $id: '#/properties/author/properties/image',
          type: 'string',
          title: 'Author\'s image',
          pattern: '^/static/(.+)$',
          description: 'A URL to the author´s image',
          default: '',
          examples: [
            '/static/nick.jpg',
          ],
        },
      },
    },
  },
};

const exportPostSchema = () => jsonPostSchema;
export { jsonPostSchema, exportPostSchema };
