name: Deploy monadical.com
on:
  push:
    branches:
      - autodeploy-test
env:
  ACTIVATE_VENV: 0
  TERM: xterm
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Detect last autodeployment
        run: |
          LAST_AUTODEPLOYED=$(git log --oneline -n 1 HEAD | grep -q "Autodeployed by git hub actions")
          echo "SKIP_STEP=$LAST_AUTODEPLOYED" >> $GITHUB_ENV
      - name: Create local changes
        if: ${{ env.SKIP_STEP }} == 1
        run: |
          pip3 install flask
          ./build
      - name: Commit filess
        if: ${{ env.SKIP_STEP }} == 1
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          git log
