name: Deploy monadical.com
on:
  push:
    branches:
      - autodeploy-test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Create local changes
        run: |
          pip3 install flask
          ./build
      - name: Commit files
        run: |
          git commit -m "Add changes" -a
          git log
