name: new-deploy
on:
  workflow_dispatch:
env:
  BRANCH: master
jobs:
  new-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to master empty commit
        run: |
          git config --local user.email "ci@monadical.com"
          git config --local user.name "CI monadical.com"
          git commit --allow-empty -m "Redeployed by git hub actions"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTODEPLOY_GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
